### ISSUE TITLE
Optional required flag for _def

### ISSUE THREAD

**Issue by MikeSorokin** [agorem/mongoose-i18n-neutral#1]
Hello! Thanks a lot for this plugin, it is quite useful for my needs.  
For some of my projects default value is not really needed, and I think I`m not the only one. Requirement of _def value need to be handled manually (either by pre-processing input data or creating additional form fields for user) and its inconvinient.  
I suggest to put flag into options, that would effect _def 'required' value.

**Comment by agorem** [comment]
Hi, Mike,
Thanks for your suggestion.
You can have this feature implemented in the next few days (release 1.1.0) through the new plugin option **defaultMandatory**. 
Regards....Antonio
