### ISSUE TITLE
Doesn't work with Mongoose 5

### ISSUE THREAD

**Issue by drugoi** [agorem/mongoose-i18n-neutral#3]
I have a mongoose version 5.0.11 installed in my project and tried to use your plugin.

When I initialize it in my source code I got this error: 
`mongoose-i18n-neutral plugin applies only to Strings`.

My schema is looks like this:
```js
  const exhibit = new Schema(
    {
      title: { type: String, i18n: true, required: true },
      description: { type: String, i18n: true, required: true },
    },
    {
      timestamps: true
    }
  );
```

I've tried a simple `String` instance and String from `Schema.Types`, but they both does not work.

I'm copied your code to my own plugin and change check for path type to simple `String`, instead of `mongoose.Schema.Types.String` and it works perfect, but I'm not sure about correctness about this decision.

**Comment by agorem** [comment]
OK. New release (1.2.0) published in npm repository.
